name: Deploy AWS Lambda

on:
  push:
    branches:
      - main

permissions:
  id-token: write       # OIDC 認証に必要
  contents: read        # リポジトリのチェックアウトに必要

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_LAMBDA_DEPLOY_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_LAMBDA_REGION }}

      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1.1.0
        with:
          function-name: lambda-sample
          code-artifacts-dir: ./dist
          handler: index.handler
          runtime: nodejs22.x
